### ISSUE TITLE
error on npm install "Unexpected value 'Hotkeys' declared by the module 'HotkeyModule'

### ISSUE THREAD

**Issue by maku** [isaacplmann/ngx-tour#1]
I did a fresh clone (on Windows 7 Pro, nodejs 6.9.1) 
when I try to do a npm install I get the following error

```
> ngc -p ./tsconfig.aot.json

Error: Unexpected value 'Hotkeys' declared by the module 'HotkeyModule'
    at d:\___mprojects\__c\angular2\ng2-tour-2\node_modules\@angular\compiler\bundles\compiler.umd.js:17816:42
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (d:\___mprojects\__c\angular2\ng2-tour-2\node_modules\@angular\compiler\bundles\compiler.umd.js:17798:56)

    at addNgModule (d:\___mprojects\__c\angular2\ng2-tour-2\node_modules\@angular\compiler\bundles\compiler.umd.js:24349:60)
    at d:\___mprojects\__c\angular2\ng2-tour-2\node_modules\@angular\compiler\bundles\compiler.umd.js:24360:16
    at Array.forEach (native)
    at _createNgModules (d:\___mprojects\__c\angular2\ng2-tour-2\node_modules\@angular\compiler\bundles\compiler.umd.js:24359:28)
    at analyzeNgModules (d:\___mprojects\__c\angular2\ng2-tour-2\node_modules\@angular\compiler\bundles\compiler.umd.js:24238:16)
    at analyzeAndValidateNgModules (d:\___mprojects\__c\angular2\ng2-tour-2\node_modules\@angular\compiler\bundles\compiler.umd.js:24248:37)
    at AotCompiler.compileAll (d:\___mprojects\__c\angular2\ng2-tour-2\node_modules\@angular\compiler\bundles\compiler.umd.js:23987:20)
Compilation failed
```

**Comment by isaacplmann** [comment]
Thanks for letting me know.  I'll work on that today.

**Comment by isaacplmann** [comment]
This should be fixed.  Apparently a `prepublish` npm script will run whenever you do `npm install`.  Kind of weird.

**Comment by maku** [comment]
I did the next try -> at this time I cloned on a mac. npm install worked. But than 
`npm run start` 
leads to the same error mentioned before

**Comment by isaacplmann** [comment]
Ha!  You're right.  I just kicked it down the road a bit.  Maybe I'll actually fix it this time.  Working on it.

**Comment by isaacplmann** [comment]
Ok, it should be fixed for real now.  You'll need to get latest, run npm install and then npm start.

I had to downgrade angular to 2.2.4.  Looks like the angular2-hotkeys dependencies doesn't play well with 2.3+.

I'm working on a PR for angular2-hotkeys now.

**Comment by maku** [comment]
Now I am a (major) step further.  But I get this:

```
[at-loader] Checking finished with 1 errors
ERROR in ./src/demo/bootstrap.aot.ts
Module not found: Error: Can't resolve './demo.module.ngfactory' in '/Users/martin/_dev/angular2/ng2-tour/src/demo'
 @ ./src/demo/bootstrap.aot.ts 1:0-62
 @ multi bootstrap.aot

ERROR in [at-loader] src/demo/bootstrap.aot.ts:1:37
    Cannot find module './demo.module.ngfactory'


```

**Comment by isaacplmann** [comment]
This is why we need a good angular 2 library seed.  Something is screwy in my configuration and I'm having trouble tracking it down.  This is the frustrating part of development.

**Comment by maku** [comment]
Funny enough I get the same type of error when I try to define a simple ng module in a clone of the base project (https://github.com/blacksonic/angular2-aot-webpack)
