### ISSUE TITLE
Object(...) is not a function

### ISSUE THREAD

**Issue by noeldelgadom** [isaacplmann/ngx-tour#120]
Hello, I am getting the following errors

Error 1

```
AppComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Object(...) is not a function
    at new TourService (ngx-tour-core.js:36)
    at _createClass (core.js:10933)
    at _createProviderInstance$1 (core.js:10907)
    at resolveNgModuleDep (core.js:10892)
    at NgModuleRef_.get (core.js:12129)
    at resolveDep (core.js:12619)
    at createClass (core.js:12489)
    at createDirectiveInstance (core.js:12326)
    at createViewNodes (core.js:13784)
    at createRootView (core.js:13673)
```

Error 2

```
zone.js:690 Unhandled Promise rejection: Object(...) is not a function ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Object(...) is not a function
    at new TourService (ngx-tour-core.js:36)
    at _createClass (core.js:10933)
    at _createProviderInstance$1 (core.js:10907)
    at resolveNgModuleDep (core.js:10892)
    at NgModuleRef_.get (core.js:12129)
    at resolveDep (core.js:12619)
    at createClass (core.js:12489)
    at createDirectiveInstance (core.js:12326)
    at createViewNodes (core.js:13784)
    at createRootView (core.js:13673) TypeError: Object(...) is not a function
    at new TourService (webpack-internal:///./node_modules/ngx-tour-core/fesm5/ngx-tour-core.js:47:75)
    at _createClass (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11149:20)
    at _createProviderInstance$1 (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11123:26)
    at resolveNgModuleDep (webpack-internal:///./node_modules/@angular/core/esm5/core.js:11108:17)
    at NgModuleRef_.get (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12345:16)
    at resolveDep (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12835:45)
    at createClass (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12705:32)
    at createDirectiveInstance (webpack-internal:///./node_modules/@angular/core/esm5/core.js:12542:37)
    at createViewNodes (webpack-internal:///./node_modules/@angular/core/esm5/core.js:14000:53)
    at createRootView (webpack-internal:///./node_modules/@angular/core/esm5/core.js:13889:5)
```

**Comment by isaacplmann** [comment]
How are you using the TourService?  What does the package.json look like?  How are you importing the TourModule?

**Comment by noeldelgadom** [comment]
Package.json
```
{
    "name": "tagrank-fe-v1",
    "version": "0.0.0",
    "license": "MIT",
    "engines": {
        "node": "6.11.2",
        "npm": "5.6.0"
    },
    "scripts": {
        "ng": "ng",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "postinstall": "ng build --aot -prod",
        "start": "node server.js"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "^5.2.11",
        "@angular/cdk": "^2.0.0-beta.12",
        "@angular/common": "^5.2.11",
        "@angular/compiler": "^5.2.11",
        "@angular/compiler-cli": "^5.2.11",
        "@angular/core": "^5.2.11",
        "@angular/forms": "^5.2.11",
        "@angular/http": "^5.2.11",
        "@angular/material": "^2.0.0-beta.12",
        "@angular/platform-browser": "^5.2.11",
        "@angular/platform-browser-dynamic": "^5.2.11",
        "@angular/platform-server": "^5.2.11",
        "@angular/router": "^5.2.11",
        "@ng-bootstrap/ng-bootstrap": "^1.0.0-beta.5",
        "@swimlane/ngx-charts": "7.3.0",
        "@types/d3-shape": "^1.2.2",
        "angular-typing-animation": "^0.4.7",
        "angularfire2": "^4.0.0-rc.0",
        "core-js": "^2.4.1",
        "d3": "^5.4.0",
        "express": "^4.16.2",
        "firebase": "^3.9.*",
        "ng2-dragula": "^1.5.0",
        "ng2-truncate": "^1.3.11",
        "ng2-validation": "^4.2.0",
        "ngx-clipboard": "^8.1.3",
        "ngx-infinite-scroll": "^0.6.1",
        "ngx-tour-core": "^3.0.0",
        "ngx-tour-md-menu": "^3.0.0",
        "prerender-node": "^3.1.1",
        "rendertron-middleware": "^0.1.2",
        "rxjs": "^5.5.11",
        "typescript": "2.4.2",
        "zone.js": "^0.8.14"
    },
    "devDependencies": {
        "@angular/cli": "^1.7.4",
        "@angular/language-service": "^4.2.4",
        "@types/jasmine": "~2.5.53",
        "@types/jasminewd2": "~2.0.2",
        "@types/node": "~6.0.60",
        "codelyzer": "~3.1.1",
        "jasmine-core": "~2.6.2",
        "jasmine-spec-reporter": "~4.1.0",
        "karma": "~1.7.0",
        "karma-chrome-launcher": "~2.1.1",
        "karma-cli": "~1.0.1",
        "karma-coverage-istanbul-reporter": "^1.2.1",
        "karma-jasmine": "~1.1.0",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.1.2",
        "ts-node": "~3.2.0",
        "tslint": "~5.3.2"
    }
}

```

app.component.ts

```
import { TourService } from 'ngx-tour-core';
import { Component } from '@angular/core';


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  constructor(
    public tourService: TourService
  ) {
    tourService.initialize([{
      anchorId: 'some.anchor.id',
      content: 'Some content',
      title: 'First',
    }, {
      anchorId: 'another.anchor.id',
      content: 'Other content',
      title: 'Second',
    }]);
    tourService.start();
    }

}

```

app.component.html

```
<app-navbar></app-navbar>
<br>
<div class="container">
    <router-outlet></router-outlet>
    <tour-step-template></tour-step-template>
</div>
```
someComponenent.component.ts

`<strong tourAnchor="some.anchor.id">Bla Bla...</strong>`

**Comment by noeldelgadom** [comment]
That worked! Thanks. I updated with https://update.angular.io/

and then did a bunch of 

`npm install --save <package>@latest`

for all the packages I had installed.

**Comment by akash-potdar7** [comment]
I am facing the same issue, with ngx-bootstrap.
angular v: 5.2
ngx-bootstrap: 2.0.5

**Comment by isaacplmann** [comment]
Check out the [changelog](https://github.com/isaacplmann/ngx-tour/blob/master/projects/ngx-tour-ngx-bootstrap/CHANGELOG.md) to see what version you want.  It looks like you probably need `2.0.0`
