### ISSUE TITLE
Extend peer dependencies to Angular 7

### ISSUE THREAD

**Issue by agil-NUBBA** [isaacplmann/ngx-tour#136]
**Issue description**

running `npm install` throws the following warning:

```
npm WARN ngx-tour-core@3.0.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-tour-core@3.0.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-tour-core@3.0.0 requires a peer of @angular/router@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-tour-ngx-bootstrap@3.0.0 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-tour-ngx-bootstrap@3.0.0 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
```
**Steps to reproduce and a minimal demo of the problem**

`npm install` with Angular 7

**Current behavior**

`npm install` shows a couple of warning due to peer dependencies.

**Expected/desired behavior**

No warnings should be shown

**Comment by isaacplmann** [comment]
@agil-NUBBA This is the kind of thing that makes for a great first PR.  I can coach you through how to do it if you want.  You could even do it directly in your web browser on github.

**Comment by bsoulier** [comment]
I can try to have a look into this. I am not really an expert on that, but just updating angular packages (on a mac) to latest version didn't do the trick.

**Comment by adripanico** [comment]
One of the dependencies (tsickle) is not compatible with Typescript >= 2.9. Angular 7 uses Typescript 3.1, so we have a big problem here.

**Comment by hakimio** [comment]
tsickle [added support for TS 3.1](https://github.com/angular/tsickle/commit/6df7ffb6709fc319574d2aaa3dbcc0616299fc68).

**Comment by adripanico** [comment]
Updating to tsickle 0.34.0 and trying to build ngx-tour:

```
$ npm run build:lib:all

> ngx-tour@0.0.1 build:lib:all /home/adrian/Source/ngx-tour
> npm run clean && npm run build:lib:core && npm run build:lib:console:base && npm run build:lib:md-menu:base && npm run build:lib:ng-bootstrap:base && npm run build:lib:ngx-bootstrap:base && npm run build:lib:ngx-popper:base


> ngx-tour@0.0.1 clean /home/adrian/Source/ngx-tour
> rm -rf dist/


> ngx-tour@0.0.1 build:lib:core /home/adrian/Source/ngx-tour
> ng build ngx-tour-core --prod && cpx projects/ngx-tour-core/CHANGELOG.md dist/ngx-tour-core/

Building Angular Package
Building entry point 'ngx-tour-core'
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Built ngx-tour-core
Built Angular Package!
 - from: /home/adrian/Source/ngx-tour/projects/ngx-tour-core
 - to:   /home/adrian/Source/ngx-tour/dist/lib

> ngx-tour@0.0.1 build:lib:console:base /home/adrian/Source/ngx-tour
> ng build ngx-tour-console --prod && cpx projects/ngx-tour-console/CHANGELOG.md dist/ngx-tour-console/

Building Angular Package
Building entry point 'ngx-tour-console'
Compiling TypeScript sources through ngc

BUILD ERROR
projects/ngx-tour-console/src/lib/tour-anchor.directive.ts(1,63): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/lib/console.module.ts(4,70): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/public_api.ts(5,15): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/lib/console.module.ts(12,41): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
projects/ngx-tour-console/src/lib/console.module.ts(13,13): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
: Can't resolve all parameters for TourAnchorConsoleDirective in /home/adrian/Source/ngx-tour/projects/ngx-tour-console/src/lib/tour-anchor.directive.ts: (?).
projects/ngx-tour-console/src/lib/console.module.ts(12,41): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
projects/ngx-tour-console/src/lib/console.module.ts(13,13): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..

Error: projects/ngx-tour-console/src/lib/tour-anchor.directive.ts(1,63): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/lib/console.module.ts(4,70): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/public_api.ts(5,15): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/lib/console.module.ts(12,41): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
projects/ngx-tour-console/src/lib/console.module.ts(13,13): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
: Can't resolve all parameters for TourAnchorConsoleDirective in /home/adrian/Source/ngx-tour/projects/ngx-tour-console/src/lib/tour-anchor.directive.ts: (?).
projects/ngx-tour-console/src/lib/console.module.ts(12,41): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
projects/ngx-tour-console/src/lib/console.module.ts(13,13): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..

    at Object.<anonymous> (/home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at /home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object.<anonymous> (/home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at /home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)

projects/ngx-tour-console/src/lib/tour-anchor.directive.ts(1,63): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/lib/console.module.ts(4,70): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/public_api.ts(5,15): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/lib/console.module.ts(12,41): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
projects/ngx-tour-console/src/lib/console.module.ts(13,13): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
: Can't resolve all parameters for TourAnchorConsoleDirective in /home/adrian/Source/ngx-tour/projects/ngx-tour-console/src/lib/tour-anchor.directive.ts: (?).
projects/ngx-tour-console/src/lib/console.module.ts(12,41): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
projects/ngx-tour-console/src/lib/console.module.ts(13,13): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..

Error: projects/ngx-tour-console/src/lib/tour-anchor.directive.ts(1,63): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/lib/console.module.ts(4,70): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/public_api.ts(5,15): error TS2307: Cannot find module 'ngx-tour-core'.
projects/ngx-tour-console/src/lib/console.module.ts(12,41): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
projects/ngx-tour-console/src/lib/console.module.ts(13,13): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
: Can't resolve all parameters for TourAnchorConsoleDirective in /home/adrian/Source/ngx-tour/projects/ngx-tour-console/src/lib/tour-anchor.directive.ts: (?).
projects/ngx-tour-console/src/lib/console.module.ts(12,41): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..
projects/ngx-tour-console/src/lib/console.module.ts(13,13): Error during template compile of 'TourConsoleModule'
  Could not resolve ngx-tour-core relative to [object Object]..

    at Object.<anonymous> (/home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ngc/compile-source-files.js:40:68)
    at Generator.next (<anonymous>)
    at /home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ngc/compile-source-files.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ngc/compile-source-files.js:3:12)
    at Object.compileSourceFiles (/home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ngc/compile-source-files.js:17:12)
    at Object.<anonymous> (/home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:31:32)
    at Generator.next (<anonymous>)
    at /home/adrian/Source/ngx-tour/node_modules/ng-packagr/lib/ng-v5/entry-point/ts/compile-ngc.transform.js:7:71
    at new Promise (<anonymous>)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-tour@0.0.1 build:lib:console:base: `ng build ngx-tour-console --prod && cpx projects/ngx-tour-console/CHANGELOG.md dist/ngx-tour-console/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngx-tour@0.0.1 build:lib:console:base script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adrian/.npm/_logs/2018-11-21T10_52_32_347Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-tour@0.0.1 build:lib:all: `npm run clean && npm run build:lib:core && npm run build:lib:console:base && npm run build:lib:md-menu:base && npm run build:lib:ng-bootstrap:base && npm run build:lib:ngx-bootstrap:base && npm run build:lib:ngx-popper:base`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngx-tour@0.0.1 build:lib:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adrian/.npm/_logs/2018-11-21T10_52_32_379Z-debug.log
```

**Comment by hakimio** [comment]
@adripanico I've created a PR. The error was not related to tsickle in any way. The issue was that libraries were copied to wrong directories.

**Comment by adripanico** [comment]
Yep, in the pasted error there is nothing related with tsickle.

I said it since during npm packages updates I saw the error describing the problem with the previous tsickle version and TS > 2.9.

Let's wait to your PR to be merged then.

Thanks!!

**Comment by bsoulier** [comment]
Very dumb question here:
Would that help on making it to work fine migrating an app using it to **Angular 7** & **Angular Material 7**?

**Comment by hakimio** [comment]
@bsoulier Yes, it should work with Angular 7 and Angular Material 7 once the PR is merged.

**Comment by isaacplmann** [comment]
New versions have been published to npm.  Thanks @hakimio for the PR!
